### ISSUE TITLE
Why the final result is different?

### ISSUE THREAD

**Issue by AmirHosseinAlikhahMishamandani** [WaterJuice/CryptLib#3]
Hi, I'm using this library in a source code ... The problem is the fact that this package removes zeroes from the final buffer ....

Software:
Input: 000102030405060708090a0b0c0d0e0f
Output from the package (strlen: 124):
fb8563ac7ba46c22244125daa793c1a79d20f9adcbe1cbd5d9d335476cca67e8e76a15a8d7c72c937e24b36a5b5ee45c7d621817f4d5be8c242bd19d5043

Online website:
The real outcome (strlen 128):
source2: https://passwordsgenerator.net/sha512-hash-generator/
FB8563AC7BA46C22244125DAA793C1A79D20F9ADCBE1CBD5D9D335476CCA67E8E76A15A8D7C72C0937E24B036A5B5EE45C7D6218170F04D5BE8C242BD19D5043

There are several "0" eliminated from it ... 
Thanks for all your efforts ...

**Comment by WaterJuice** [comment]
Without seeing your source code I can't determine why the zeros are missing. If you run the test program that comes with the library you'll see it produces the correct result:

$ ./Sha512String 000102030405060708090a0b0c0d0e0f
fb8563ac7ba46c22244125daa793c1a79d20f9adcbe1cbd5d9d335476cca67e8e76a15a8d7c72c0937e24b036a5b5ee45c7d6218170f04d5be8c242bd19d5043

All I can assume is your binary to hex string converter is broken. Remember the input is binary, even though you have made it look like a hex input, it it is 32 bytes. The output displayed is the hex conversion of the 64 output bytes.

If you post your code where its using the function and displaying the output I may be able to help you find whats gone wrong.

**Edited**
I've seen your code example now and can see the problem. You are printing each byte of output with printf using %x. This will print only 1 character where the value of the byte is less than 0x10. So if the byte is 0x07 it will simply print "7". Which is why your final output seems to be dropping zeros.
To fix this you need to force printf to always print 2 characters. Change "%x" to "%2.2x" and you will get the correct printing.

**Comment by AmirHosseinAlikhahMishamandani** [comment]
thank you for your fast and correct answer ... Awesome ...
